### ISSUE TITLE
Considering migrating from a live stream to a podcast

### ISSUE THREAD

**Issue by ckipp01** [ckipp01/tooling-talks#2]
I've recently been putting some thought into how tooling-talks is currently done and how I'd like to continue to do them moving forward. My hope was that doing a live stream would provide a great way to engage with the community and also allow for questions in real-time. From the feedback that I've been receiving so far, it seems that the majority of people listen to the talk after the stream and mostly just listen to it in the background. This makes me wonder if it'd be better suited to simply be a podcast. This would allow for me to focus more on audio quality, and less about the details of streaming. This would also be quite a bit easier. I'd love to input that listeners have about this. Would the live stream be missed? Or would the majority of people just be fine with a podcast since that's the way the engage with the content anyway.

Thanks!

**Comment by gabro** [comment]
I personally listen to the recording, in background, so yeah, I think a podcast would serve the same purpose for me

**Comment by ckipp01** [comment]
Awesome, thanks for the input. I plan on switching, and for each talk I'll actually create a discussion for it where I'll announce each speaker the month before and collect questions there and allow for a discussion to happen. Hopefully this will still allow for some interaction and also allow me to focus on the audio quality!
